### PR TITLE
Rebuilding for Titanium SDK 6.0.0+

### PR DESCRIPTION
**Pull request by gimdongwoo**

### CODE REVIEW

**Comment by netoramalho** [comment]
Thanks!

**Comment by timoa** [comment]
Hi Guys!

Any chance to see this commit approved?

Kind Regards

Damien

**Comment by gimdongwoo** [comment]
I want to merge.

**Comment by iskugor** [comment]
Sorry guys, I'm not using Titanium anymore (except in old projects) so you might want to use someone else fork. Thanks.

Cheers, Ivan.

**Comment by gimdongwoo** [comment]
If you add me as a committer, I can manage it.

**Pull request merged**
